// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkhnajhaocemjgedksvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1raG5hamhhb2NlbWpnZWRrc3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NzI3NDcsImV4cCI6MjA2NTM0ODc0N30.ZMJsqWVjWApl0yFiXZp7btC2SMrXL71wKm4JztzSHY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);